##########################################################
##            Default environment yaml file             ##
##########################################################
# NOTE: See validation_templates/environment_template.py # 
#       for the parameter restrictions                   #
##########################################################

window_dimensions : [1280, 720]
plane_pos_scale : 2
ground:
    sprite : "assets/floor.png"
    height : 50 # number of pixels from the bottom
    collision_elevation : 670 # number of pixels from the top
background:
    sprite : "assets/background.png"
